version: '3'

services:

  mysql-development:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "3338:3306"
    volumes:
      - db_data_mysql_crud:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data_mysql_crud: null
